spring:
  neo4j:
    uri: bolt://localhost:7687

    authentication:
      username: neo4j
      password: dockerCompose
#logging.level:
#    org.neo4j.driver.internal.async.outbound.OutboundMessageHandler: debug
